import { NextResponse } from 'next/server';
import { createClient } from '@/utils/supabase/server';

export async function POST(req: Request) {
  try {
    const { id, source, target } = await req.json();
    const supabase = await createClient();
    
    // Explicitly pass id if generated by React Flow
    const { data, error } = await supabase.from('mindmap_edges').insert({
      id, source, target
    }).select().single();

    if (error) throw error;
    return NextResponse.json({ success: true, edge: data });
  } catch (err: any) {
    return NextResponse.json({ error: err.message }, { status: 500 });
  }
}
